### ISSUE TITLE
Critters dont work if the url has a prefix

### ISSUE THREAD

**Issue by TheElegantCoding** [astro-community/AstroCritters#306]
if you have a build that puts a url in front of the css, this is the `assetsPrefix` option in astro, you will have this difference

```html
<link rel="stylesheet" href="http://localhost:4321/_astro/index.Bd8XMnIY.css">

<link rel="stylesheet" href="/_astro/index.Bd8XMnIY.css">
```

and when you have a prefix with the url or domain dont works well, and don't inline nothing

**Comment by NikolaRHristov** [comment]
I'll take a look. Thank you.

**Comment by TheElegantCoding** [comment]
Critters has an option for this, you can pass `publicPath` as a string that will be remove from the original path, just need to add this option in the plugin for these cases

**Comment by NikolaRHristov** [comment]
Does it work if you pass it in the integration's options? You can override them like this:

```ts
export default {
 	integrations: [
 		(await import("@playform/inline")).default({
 			Critters: { publicPath: "https://yoururl.com" },
 		}),
 	],
 };
```

**Comment by TheElegantCoding** [comment]
yeah that works, didn't know that you can override the critters options, is not as an example in the readme
